wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    code_path: code/semanticdebugger/debug_algs/index_based/biencoder.py
    framework: huggingface
    huggingface_version: 2.9.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1634201353
    t:
      1:
      - 1
      - 5
      - 11
      2:
      - 1
      - 5
      - 11
      3:
      - 2
      4: 3.6.9
      5: 0.12.4
      6: 2.9.0
      8:
      - 5
batch_size:
  desc: null
  value: 64
dim_vector:
  desc: null
  value: 128
droprate:
  desc: null
  value: 0
ds_dir_path:
  desc: null
  value: exp_results/supervision_data/1014_init_mean_dm_simple/
eval_per_steps:
  desc: null
  value: 100
hidden_dim:
  desc: null
  value: -1
lr:
  desc: null
  value: 0.001
memory_encoder_path:
  desc: null
  value: exp_results/supervision_data/1014_init_mean_dm_simple.mem_encoder.pt
memory_index_path:
  desc: null
  value: exp_results/supervision_data/1014_init_mean_dm_simple.memory.index
memory_input_dim:
  desc: null
  value: 1536
n_steps:
  desc: null
  value: 3000
neg_size:
  desc: null
  value: 8
num_ds_dev_file:
  desc: null
  value: 3
num_ds_train_file:
  desc: null
  value: 24
pos_size:
  desc: null
  value: 8
qry_size:
  desc: null
  value: 8
query_delta:
  desc: null
  value: false
query_encoder_path:
  desc: null
  value: exp_results/supervision_data/1014_init_mean_dm_simple.qry_encoder.pt
query_input_dim:
  desc: null
  value: 3072
query_only_after:
  desc: null
  value: false
query_only_before:
  desc: null
  value: false
run_mode:
  desc: null
  value: train
seed:
  desc: null
  value: 42
train_args_path:
  desc: null
  value: exp_results/supervision_data/1014_init_mean_dm_simple.train_args.json
use_cuda:
  desc: null
  value: true
wandb:
  desc: null
  value: true
