wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: huggingface
    huggingface_version: 2.9.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1634177178
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.6.9
      5: 0.12.4
      6: 2.9.0
      8:
      - 5
